name: C/C++ CI

on:
  push:
    branches: [ "improvements" ]
  pull_request:
    branches: [ "improvements" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
