name: norminette
on:
  push:
    branches: [ "improvements" ]
  pull_request:
    branches: [ "improvements" ]
  workflow_dispatch:
jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install norminette
    - name: Lint with norminette
      run: |
        norminette .
